# Generated by Django 5.0 on 2023-12-25 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhod',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='adminhod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='adminhod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_app.subjects', verbose_name='урок'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='attendance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.attendance', verbose_name='посещаемость'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='status',
            field=models.BooleanField(default=False, verbose_name='присутствие'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_app.students', verbose_name='студент'),
        ),
        migrations.AlterField(
            model_name='feedbackstaffs',
            name='feedback',
            field=models.TextField(verbose_name='текст уведомления'),
        ),
        migrations.AlterField(
            model_name='feedbackstaffs',
            name='feedback_reply',
            field=models.TextField(verbose_name='ответ на обратную связь'),
        ),
        migrations.AlterField(
            model_name='feedbackstaffs',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.staffs', verbose_name='персонал'),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='feedback',
            field=models.TextField(verbose_name='текст уведомления'),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='feedback_reply',
            field=models.TextField(verbose_name='ответ на обратную связь'),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.students', verbose_name='студент'),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_date',
            field=models.CharField(max_length=255, verbose_name='дата увольнения'),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_message',
            field=models.TextField(verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_status',
            field=models.BooleanField(default=False, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.staffs', verbose_name='персонал'),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_date',
            field=models.CharField(max_length=255, verbose_name='дата отчисления'),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_message',
            field=models.TextField(verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_status',
            field=models.BooleanField(default=False, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.students', verbose_name='студент'),
        ),
        migrations.AlterField(
            model_name='notificationstaffs',
            name='message',
            field=models.TextField(verbose_name='текст уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationstaffs',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.staffs', verbose_name='персонал'),
        ),
        migrations.AlterField(
            model_name='notificationstudent',
            name='message',
            field=models.TextField(verbose_name='текст уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationstudent',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.students', verbose_name='студент'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='students',
            name='address',
            field=models.TextField(verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='students',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='students',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_app.courses', verbose_name='название курса'),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(max_length=255, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='students',
            name='session_end_year',
            field=models.DateField(verbose_name='конец учебного года'),
        ),
        migrations.AlterField(
            model_name='students',
            name='session_start_year',
            field=models.DateField(verbose_name='начало учебного года'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_app.courses', verbose_name='название курса'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
